import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { DiagnosticReport, DiagnosticStatus } from './entities/diagnostic-report.entity';
import { TelemetryGateway } from '../../gateway/telemetry.gateway';
import { GoogleGenAI } from '@google/genai';
import axios from 'axios';

@Injectable()
export class InferenceProcessor {
    constructor(
        @InjectRepository(DiagnosticReport)
        private readonly reportRepo: Repository<DiagnosticReport>,
        private readonly gateway: TelemetryGateway,
    ) { }

    async process(data: { reportId: string, imageUrl?: string, base64Image?: string, mimeType?: string, lat?: string, lon?: string, cropType?: string }): Promise<any> {
        const reportId = data.reportId;
        console.log(`[AI Worker] Starting immediate inference for Report ID: ${reportId}`);

        // Update DB to Processing
        await this.reportRepo.update(reportId, { status: DiagnosticStatus.PROCESSING });

        // Emit real-time status update to frontend
        this.gateway.server.emit('inference_progress', { reportId, status: 'PROCESSING', progress: 10 });

        const { base64Image, mimeType, lat, lon, cropType } = data;
        let finalOutput: any = null;
        const apiKey = process.env.GEMINI_API_KEY || '';

        // --- VALIDATE API KEY ---
        if (!apiKey) {
            finalOutput = null;
            await this.reportRepo.update(reportId, { status: DiagnosticStatus.FAILED });
            this.gateway.server.emit('inference_progress', { reportId, status: 'FAILED', error: "AI Engine offline. Missing GEMINI_API_KEY." });
            return;
        }

        // --- FETCH REAL-TIME ENVIRONMENTAL DATA (OPEN-METEO) ---
        let weatherContext = "Real-time weather data unavailable (no coordinates provided).";
        if (lat && lon) {
            try {
                this.gateway.server.emit('inference_progress', { reportId, status: 'PROCESSING', progress: 20 });
                const weatherUrl = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,precipitation&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=auto`;
                const weatherRes = await axios.get(weatherUrl);
                const current = weatherRes.data.current;
                const daily = weatherRes.data.daily;
                weatherContext = `LOCAL WEATHER AND FORECAST FOR COORDINATES (${lat}, ${lon}):
- Current Conditions: Temperature ${current.temperature_2m}°C, Humidity ${current.relative_humidity_2m}%, Precipitation ${current.precipitation}mm
- Next 3 Days Forecast: 
  Day 1: ${daily.temperature_2m_max[1]}°C max, ${daily.precipitation_sum[1]}mm rain
  Day 2: ${daily.temperature_2m_max[2]}°C max, ${daily.precipitation_sum[2]}mm rain
  Day 3: ${daily.temperature_2m_max[3]}°C max, ${daily.precipitation_sum[3]}mm rain
`;
                console.log(`[Diagnostic Lab] Live Weather Integrated for Neural Inference: ${current.temperature_2m}°C, ${current.relative_humidity_2m}% HR`);
            } catch (err) {
                console.error("[AI Worker] Failed to fetch weather data from Open-Meteo", err.message);
                weatherContext = "Real-time weather data unavailable (fetch failed).";
            }
        }

        const cropHint = cropType && cropType !== "Potato" && cropType !== "None" ? `The user suspects or identified this plant as: ${cropType}. Use this as a strong hint, but verify it via the image characteristics.` : `The crop type was not provided. You MUST identify the crop species accurately.`;

        // --- REAL-TIME MULTIMODAL PLANT DISEASE ANALYSIS ENGINE ---
        try {
            this.gateway.server.emit('inference_progress', { reportId, status: 'PROCESSING', progress: 30 });
            const ai = new GoogleGenAI({ apiKey });

            const promptString = `You are the core reasoning engine of a production agricultural diagnostic platform called AgroVision AI, developed for the project “A Vision-Driven Agro Diagnostic Framework Using Machine Learning.” Your responsibility is to generate accurate real-time crop health diagnostics using outputs from trained machine learning models, image analysis features, and environmental context. 

When a plant image is uploaded, the system will first provide the predicted crop type generated by the crop classification model along with a confidence score. You must strictly use this crop classification result and must never assume or guess the crop type independently. If the crop classification confidence is below seventy percent, the system must mark the crop identification as uncertain and request a clearer image instead of generating a diagnosis. 

Once the crop species is confirmed, analyze the visual features detected by the disease detection model such as lesion patterns, discoloration regions, chlorosis, necrotic patches, fungal growth structures, pest damage, leaf deformation, and abnormal textures. The disease prediction must always be restricted to diseases that are scientifically associated with the detected crop species, ensuring that cross-crop predictions are impossible. For example, if the crop is cotton, the system must only evaluate cotton diseases such as cotton leaf curl virus, bacterial blight, fusarium wilt, or alternaria leaf spot, and it must never output diseases belonging to other crops such as tomato or potato. If the disease detection confidence is below sixty percent, the system must return “no confident disease detected” instead of producing an incorrect result. 

After identifying the most probable disease, estimate infection severity by analyzing the percentage of infected plant area identified by the segmentation model and classify the severity as low, moderate, high, or critical depending on the spread of lesions across the leaf surface. Provide a concise explainable-AI reasoning that references the visual evidence used for diagnosis, such as necrotic clusters, mosaic patterns, mildew formation, curling veins, or fungal lesions. 

Next, incorporate environmental intelligence by evaluating available weather and soil parameters including temperature, humidity, rainfall, soil moisture, and wind conditions to determine whether the environment favors disease development. If weather conditions increase the probability of pathogen growth, raise the predicted risk level accordingly and explain how environmental factors influence disease spread. 

After confirming the disease and severity, generate crop-specific treatment recommendations including chemical control options such as pesticide name, active ingredient, dosage, and spray interval, along with organic or integrated pest management methods such as neem oil sprays, biological control agents, resistant crop varieties, crop rotation, and improved irrigation practices. Treatment recommendations must always match the detected crop and disease and must never repeat generic instructions for unrelated crops. 

Finally, estimate the agricultural impact by predicting the potential yield loss percentage if the disease is left untreated and classify the overall threat level as low, medium, high, or critical. If the system does not have sufficient evidence for disease identification, it must explicitly state that the diagnosis is uncertain rather than generating misleading analysis. The ultimate goal of the system is to deliver accurate, crop-specific, evidence-based plant disease diagnostics that can be reliably used in a real-time precision agriculture decision support platform.

${weatherContext}
${cropHint}

JSON FORMAT SCHEMA (STRICTLY RETURN ONLY THIS JSON OBJECT, NO MARKDOWN TAGS, NO OTHER TEXT):
{
  "crop": "Extracted Crop Name",
  "cropScientificName": "Scientific Name of Crop",
  "cropConfidence": 0.95,
  "disease": "Specific Disease Name or 'Healthy'",
  "diseaseScientificName": "Pathogen Scientific Name or 'None'",
  "diseaseType": "Viral/Fungal/Bacterial/Pest/Nutrient/None",
  "diseaseConfidence": 0.92,
  "severity": "Low/Moderate/High/Critical/None",
  "riskLevel": "Low/Medium/High/Critical/None",
  "affectedAreaPercent": 40,
  "xaiInsight": "Detailed visual cues observed driving this diagnosis. Why did you choose this disease?",
  "message": null,
  "healthScore": 60,
  "recommendations": {
    "pesticides": [
       { "name": "Pesticide Name", "activeIngredient": "Ingredient", "dosage": "Exact Dose", "frequency": "Interval", "safety": "Precautions" }
    ],
    "organic": ["Organic method 1", "Organic method 2"],
    "prevention": ["Prevention 1", "Prevention 2"],
    "preventiveSpraySchedule": ["Schedule 1", "Schedule 2"],
    "smartIrrigationAdvice": "Irrigation advice based on weather and disease."
  },
  "insights": {
    "spreadProbability": "High/Medium/Low based on weather",
    "yieldImpact": "Estimated yield loss %",
    "environmentalFactor": "Explanation of how the current weather affects this disease right now.",
    "next7DayForecast": "What to look out for based on next 3 day rain/temp forecast."
  }
}`;

            this.gateway.server.emit('inference_progress', { reportId, status: 'PROCESSING', progress: 50 });
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: [
                    {
                        role: 'user',
                        parts: [
                            {
                                inlineData: {
                                    data: base64Image,
                                    mimeType: mimeType || 'image/jpeg'
                                }
                            },
                            { text: promptString }
                        ]
                    }
                ],
                config: {
                    responseMimeType: "application/json",
                    temperature: 0.1
                }
            });

            const rawJson = response.text;
            if (rawJson) {
                // Remove markdown code block syntax if Gemini wrapped it
                const jsonString = rawJson.replace(/```json/g, '').replace(/```/g, '').trim();
                finalOutput = JSON.parse(jsonString);
            }
            this.gateway.server.emit('inference_progress', { reportId, status: 'PROCESSING', progress: 95 });

            if (!finalOutput || !finalOutput.disease) {
                throw new Error("Invalid formulation of AI response.");
            }

            if (finalOutput.cropConfidence < 0.70) {
                throw new Error("Crop identification uncertain");
            }

            if (finalOutput.diseaseConfidence && finalOutput.disease !== 'Healthy' && finalOutput.diseaseConfidence < 0.60) {
                throw new Error("No confident disease detected");
            }

            // Update DB to Complete with the exact AI JSON payload
            await this.reportRepo.update(reportId, {
                status: DiagnosticStatus.COMPLETED,
                diseasePredictedName: finalOutput.disease,
                confidenceScore: finalOutput.diseaseConfidence,
                fullResult: finalOutput
            });

            console.log(`[AI Worker] Finished inference for ID: ${reportId}. Result: ${finalOutput.disease} on ${finalOutput.crop}`);

            // Final emission over real-time websockets back to the React UI
            this.gateway.server.emit('inference_progress', {
                reportId,
                status: 'COMPLETED',
                result: finalOutput
            });

            return { reportId, outcome: finalOutput };

        } catch (err: any) {
            console.error("[AI Worker] Gemini Execution Failed:", err);

            // Log Error in DB
            await this.reportRepo.update(reportId, { status: DiagnosticStatus.FAILED });

            const errorMsg = err.message || 'Unknown network error. Please ensure GEMINI_API_KEY is robust.';
            const isKnownError = errorMsg === "Crop identification uncertain" || errorMsg === "No confident disease detected" || errorMsg === "Invalid formulation of AI response.";

            // Emit Failure properly to Frontend
            this.gateway.server.emit('inference_progress', {
                reportId,
                status: 'FAILED',
                error: isKnownError ? errorMsg : "AI Infrastructure error: " + errorMsg
            });
            return null;
        }
    }

    async chat(message: string, context?: any): Promise<any> {
        const apiKey = process.env.GEMINI_API_KEY || '';
        if (!apiKey) {
            throw new Error("AI Engine offline. Missing GEMINI_API_KEY.");
        }

        const ai = new GoogleGenAI({ apiKey });

        const systemPrompt = `You are a multilingual voice-enabled agricultural AI assistant integrated into the AgroVision AI platform developed for the project “A Vision-Driven Agro Diagnostic Framework Using Machine Learning.” The assistant must operate through a feature called Voice Matrix, which enables full conversational interaction using both text and voice in the language selected by the user. When a user selects a language from the language selector (for example English, Telugu, Hindi, Tamil, Kannada, Malayalam, Marathi, or Bengali), the assistant must immediately switch the entire conversation context to that language and continue responding exclusively in the selected language for both text responses and voice output. The system must not default to English once a different language is selected. The assistant should convert user voice input into text using speech recognition, automatically detect whether the speech matches the selected language, and process the query accordingly. The response must then be generated in the same selected language and converted into natural speech using text-to-speech, ensuring the assistant speaks the language fluently instead of only displaying translated text. Once the language is selected, the assistant must also maintain that language as the conversation context across the entire session, meaning follow-up questions, crop analysis explanations, pesticide recommendations, weather warnings, and farming advice must continue in the same language until the user manually changes the language. If the user uploads a crop image using the camera icon in the chat input, the assistant must analyze the image using the AgroVision AI diagnostic engine and provide results including crop name, detected disease, confidence level, severity index, treatment recommendations, pesticide usage instructions, and prevention strategies in the currently selected language and also speak the result aloud using voice synthesis in that language. The system must ensure that farmers who speak regional languages receive fully localized explanations without switching back to English. The assistant should maintain conversational continuity so farmers can ask follow-up questions about treatments, irrigation schedules, fertilizer recommendations, or disease prevention and receive answers in the same language. If the user changes the language from the selector, the assistant must seamlessly switch both text output and spoken voice output to the newly selected language while preserving the previous conversation context. The goal is to ensure that Voice Matrix functions as a fully multilingual conversational agricultural advisor where farmers can speak, listen, and interact with the AI assistant entirely in their preferred language while receiving accurate crop diagnostics and farming guidance.

${context ? `[CURRENT DIAGNOSTIC/ENVIRONMENT CONTEXT]: ${JSON.stringify(context)}` : ''}`;

        try {
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: [
                    {
                        role: 'user',
                        parts: [
                            { text: message }
                        ]
                    }
                ],
                config: {
                    temperature: 0.3,
                    systemInstruction: systemPrompt
                }
            });

            return {
                reply: response.text
            };
        } catch (err: any) {
            console.error("[Assistant Worker] Gemini Chat Failed:", err);
            throw new Error("Chat assistant error: " + err.message);
        }
    }
}
